version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    # Trwały wolumin z danymi + automatyczny import z JSON
    volumes:
      - ./mongo-data:/data/db
      - ./database_init:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_DATABASE: mongo_database

  api:
    build: .
    container_name: api
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - PORT=5000
    ports:
      - "5000:5000"
